### PR TITLE
Fix potential issues with execution, clean up some docs

### LINKED ISSUE #1: Hardcoded python shebang is not universal
(Firstly, thanks for the great workflow!)

# Issue

The hard-coded shebang `#!/usr/local/bin/python3` is not universal for all python installations. This causes the workflow to fail.

posix_spawn_error

# Notes

I realise that it is suggested to install python via homebrew, but that is extra work, requires extra storage, and could very easily cause conflicts with existing python installations. For example, I am using the Anaconda installation of python at `/Users/markus/opt/anaconda3/bin/python3`.

# Suggestions

Changing the shebang manually to `#!/Users/markus/opt/anaconda3/bin/python3` works.

However, it would make the most sense to use environment variable `#!/usr/bin/env python3`. As noted in some forum posts, Alfred doesn't seem to [support this](https://www.alfredforum.com/topic/1870-running-a-python-script-shebang-and-environment/) though, or only in [certain circumstances](https://www.alfredforum.com/topic/14685-alfred-uses-python-37-instead-of-382/).

It might be worth investigating a workaround. For example, a bash shell with access to `/usr/bin/env python3` could call the python scripts. Alternatively, the python3 executable path could be configured upon installation of the workflow.

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Recently this workflow stopped working for me, and it turns out it was due to my having the `python3` bin in a different place, but still on my `$PATH`.

Here’s what I tweaked:

* Made the scripts portable, so they will use whatever `python3` is on the user’s `$PATH`
* Ensured they all are executable
* Cleaned up some docs

### CODE REVIEW

**Comment by blueset** [comment]
Hi Jeff,

Thanks for the PR! I’m linking this to #1 for the same problem addressed.

Regarding changing the shebang path in the Python scripts, as reported in the last section of #1, `#!/usr/bin/env python3` is not working for certain conditions of Python installation. Due to the multiple factors of user’s Python installation (Homebrew, Port, Conda/Anaconda, pyenv, etc.) and shell environment (zsh, bash, fish, etc.). It seems to be hard to find a solution for this that would work for all conditions. 

I’m labeling this issue with `help wanted` in hope of a better solution can be found.

**Comment by jeffbyrnes** [comment]
@blueset hmm, `pyenv` is certainly widely used. Still, if someone is using `pyenv` for their Python dev, but _also_ installs Python via Homebrew, they should be all good with this shebang.

That is, this _should_ solve for _more_ cases than the current hardcoded shebang.

**Comment by blueset** [comment]
The problem for is `#!/usr/bin/env python` isn’t always working in Alfred, as it somewhat fails to reflect the complete `$PATH` to the script running. Quoting from #1:

> However, it would make the most sense to use environment variable `#!/usr/bin/env python3`. As noted in some forum posts, Alfred doesn't seem to [support this](https://www.alfredforum.com/topic/1870-running-a-python-script-shebang-and-environment/) though, or only in [certain circumstances](https://www.alfredforum.com/topic/14685-alfred-uses-python-37-instead-of-382/).

We can see from the post in the second link, the `$PATH` Alfred provides does not even include `/usr/bin/local`, which is where Homebrew pour binary symlinks to.

> [...] if someone is using `pyenv` for their Python dev, but _also_ installs Python via Homebrew [...]

If they have “also installed Python via Homebrew”, the script should be able to find the correct Python 3 via the current shebang `#!/usr/bin/local/python3` which is exactly where Python binary symlink is located for Homebrew installations.

As the README already suggests to install Python via Homebrew, I think it is only reasonable to introduce another solution if it **confirms to work with what has already been working** and, upon that, enables other situations as well.

**Comment by jeffbyrnes** [comment]
So, I have `python3` installed via Homebrew, and with this shebang, `#!/usr/bin/env python`, it works well.

I hear you on `/usr/local/bin` being the default locale for Homebrew to link things, but it can be changed (which I have done in some cases).

I’m curious, what situations have you seen Alfred not respecting the `$PATH` that is set for the current user?

**Comment by blueset** [comment]
First of all, testing on my local Alfred setup running a script filter with the following content using both `/bin/bash` and /bin/zsh` as language:

```bash
echo "{\"items\":[{\"title\":\"$PATH\"}]}"
```

yields

```bash
/usr/bin:/bin:/usr/sbin:/sbin
```

which is far too different from what I get by running `echo $PATH` in my Terminal.app.

```
/usr/local/heroku/bin:/Library/TeX/texbin:/usr/local/sbin:/usr/local/opt/gettext/bin:/usr/local/opt/openssl/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin
```

--- 

Also, if you would ever bother to check the links in my previous comment, it is not hard to see the following replies to the forum thread:

> Conclusion: Alfred is using zsh shell which I am also using but why it PATH in Python script is different form PATH in shell?

> > Ok got it, but this means that Alfred uses own env? Is there a way to configure Alfred's zsh env? 
>
> Not really. Alfred uses the same env as everything else. Your shell uses its own env.

> Alfred, indeed, does not load your local profile. Try providing the full path to the python executable that you wish to use when executing the script

> Looks like /usr/bin/env python3 is not the way to go since default paths are not including /usr/bin/local which brew populates with python3 which appears to be the most common way to get python3 into OSX.

**Comment by jeffbyrnes** [comment]
@blueset ack, sorry! I missed that part when I read through the links you provided. I can replicate exactly what you quote above, so I set to figure out why this works in spite of that, and, turns out, macOS 10.15 Catalina comes with Python 3 installed:

```bash
🕙 10:16:28 rbyrnes in ~
♠ /usr/bin/python3 -V
Python 3.7.3
```

So! With that in mind, what would you like to do?

**Comment by blueset** [comment]
I’m keen on exploring options that would include as many sources of `$PATH` as feasible in to the bash script before calling `python` while prevent it from breaking when some or all of the sources are not there. I’m not sure is that’s something easy to achieve with shell scripts.

**Comment by jeffbyrnes** [comment]
Hmmmm…

One could use `bash` to check some known-good paths for `python`, check the version, and, if all is well, launch the actual python script, passing along the query.

A bit janky, but avoids `$PATH` issues w/ Alfred being different from the current user env.

**Comment by jeffbyrnes** [comment]
Only closed b/c I’m renaming master to main, but I’ll keep this one as-is to avoid recreating this.

**Comment by jeffbyrnes** [comment]
Looking at this afresh, the simplest is probably to either:

* Keep the portable shebang I changed here
* Switch to `/usr/bin/python3`, which is available as of macOS 10.15
* Revert back to Homebred-installed `/usr/local/bin/python3`
    * Caveat: this does not account for someone who has decided to install Homebrew bins to a nonstandard location

I’m good any which way!

**Comment by blueset** [comment]
Since in Catalina, `python3` (`/usr/bin/python3`) is already available as a part of the Command Line Tools (CLTs), and the CLTs are required to install Homebrew anyway, along with the fact that Catalina is already taking 2/3 of the macOS market share by November, I think it is a reasonable choice to switch to `/usr/bin/python3` for this.

Ref: macOS market share chart from StatCounter.

[image](https://gs.statcounter.com/macos-version-market-share/desktop/worldwide/#monthly-202011-202012-bar)

**Comment by jeffbyrnes** [comment]
Updated to use `/usr/bin/python3` instead of `/usr/bin/env` or `/usr/bin/local/python3`. I think this is a great way to do it!

**Comment by blueset** [comment]
Awesome! I’ll get this merged. Thanks for the PR!

**Pull request merged**
